name: Cache Demo Workflow

on:
  workflow_dispatch:  # allows manual triggering
  push:               # triggers on push

jobs:
  cache-example:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Prime cache (required id)
      - name: Prime cache step
        id: prime-cache-824f579
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache-824f579
          restore-keys: |
            cache-824f579

      # Step 3: Echo cache hit/miss result
      - name: Echo cache result
        run: |
          if [ "${{ steps.prime-cache-824f579.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Step 4: Install dependencies (will use cache if available)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

